import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { Clock, MapPin, MessageCircle, Phone, Star } from "lucide-react";
import { MediaPlaceholder } from "@/components/kheni/media-placeholder";
import { Container } from "@/components/ui/container";
import { Section } from "@/components/ui/section";
import { locations } from "@/content/site";
import { whatsappUrl } from "@/lib/links";

export function generateStaticParams(){return locations.map(location=>({slug:location.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const location=locations.find(item=>item.slug===slug);if(!location)return{};return{title:`Dentist in ${location.shortName}, Surat | Kheni Dental`,description:`Visit Kheni Dental in ${location.shortName}, Surat. Find the clinic address, phone number, directions and appointment options.`}}
export default async function LocationPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const location=locations.find(item=>item.slug===slug);if(!location)notFound();const message=`Hello Kheni Dental, I would like to book an appointment at the ${location.shortName} branch. Please share the available options.`;return <><section className="bg-ink text-white"><Container width="7xl" className="grid min-h-[64vh] items-center gap-12 py-16 lg:grid-cols-[1fr_.9fr] lg:py-24"><div><p className="text-xs font-semibold uppercase tracking-[.22em] text-gold">Kheni Dental · Surat</p><h1 className="mt-5 font-serif text-5xl leading-[.95] tracking-[-.04em] sm:text-6xl">{location.shortName}</h1><p className="mt-6 max-w-xl text-lg leading-8 text-white/60">{location.note}</p>{location.rating&&<div className="mt-6 inline-flex items-center gap-3 rounded-full border border-gold/20 px-4 py-2 text-sm"><Star className="size-4 fill-current text-gold"/><strong>{location.rating}</strong><span className="text-white/50">{location.reviewCount} {location.reviewSource} ratings</span></div>}<div className="mt-8 flex flex-wrap gap-3"><a href={whatsappUrl(message,location.whatsappNumber)} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-full bg-gold px-5 py-3 text-sm font-semibold text-ink"><MessageCircle className="size-4"/>WhatsApp branch</a><a href={location.mapsUrl} target="_blank" rel="noreferrer" className="rounded-full border border-white/15 px-5 py-3 text-sm font-semibold">Get directions</a></div></div><MediaPlaceholder label={`${location.shortName} clinic exterior and interior`} className="min-h-[30rem]"/></Container></section><Section spacing="lg"><Container width="7xl"><div className="grid gap-5 md:grid-cols-3"><div className="rounded-2xl border border-border bg-card p-6"><MapPin className="size-5 text-gold"/><h2 className="mt-4 font-serif text-2xl">Address</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">{location.address}</p></div><a href={`tel:${location.phoneHref}`} className="rounded-2xl border border-border bg-card p-6"><Phone className="size-5 text-gold"/><h2 className="mt-4 font-serif text-2xl">Call</h2><p className="mt-3 text-sm text-muted-foreground">{location.phoneDisplay}</p></a><div className="rounded-2xl border border-border bg-card p-6"><Clock className="size-5 text-gold"/><h2 className="mt-4 font-serif text-2xl">Visiting hours</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">{location.hours}</p></div></div></Container></Section></>}
