import type { Metadata } from "next";
import { Clock, Mail, MapPin, MessageCircle, Phone } from "lucide-react";
import { PageHero } from "@/components/kheni/page-hero";
import { ConsultationForm } from "@/components/kheni/consultation-form";
import { Container } from "@/components/ui/container";
import { Section } from "@/components/ui/section";
import { site } from "@/content/site";
import { whatsappUrl } from "@/lib/links";
export const metadata:Metadata={title:"Contact & Book Consultation",description:"Contact Kheni Elite Dental & Implant Center in Surat by phone, WhatsApp or appointment request."};
export default function ContactPage(){return <><PageHero eyebrow="Contact" title="A simple next step." copy="Call, WhatsApp or request appointment options. Replace all contact placeholders with verified clinic details before launch."/><Section spacing="lg"><Container width="7xl"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div className="space-y-4"><a href={`tel:${site.phoneHref}`} data-track="phone_click" data-placement="contact_page" className="flex gap-4 rounded-2xl border border-border bg-card p-5"><Phone className="size-5 text-gold"/><div><p className="font-medium">Call clinic</p><p className="mt-1 text-sm text-muted-foreground">{site.phoneDisplay}</p></div></a><a href={whatsappUrl()} target="_blank" rel="noreferrer" data-track="whatsapp_click" data-placement="contact_page" className="flex gap-4 rounded-2xl border border-border bg-card p-5"><MessageCircle className="size-5 text-gold"/><div><p className="font-medium">WhatsApp</p><p className="mt-1 text-sm text-muted-foreground">Request appointment options</p></div></a><a href={site.mapsUrl} target="_blank" rel="noreferrer" data-track="directions_click" data-placement="contact_page" className="flex gap-4 rounded-2xl border border-border bg-card p-5"><MapPin className="size-5 text-gold"/><div><p className="font-medium">Clinic address</p><p className="mt-1 text-sm leading-6 text-muted-foreground">{site.address}</p></div></a><div className="flex gap-4 rounded-2xl border border-border bg-card p-5"><Clock className="size-5 text-gold"/><div><p className="font-medium">Working hours</p><p className="mt-1 text-sm text-muted-foreground">{site.hours}</p></div></div><a href={`mailto:${site.email}`} className="flex gap-4 rounded-2xl border border-border bg-card p-5"><Mail className="size-5 text-gold"/><div><p className="font-medium">Email</p><p className="mt-1 text-sm text-muted-foreground">{site.email}</p></div></a></div><ConsultationForm/></div></Container></Section></>}
