import Link from "next/link";
import { ArrowRight, Award, Globe2, HeartHandshake, MessageCircle, Microscope, ShieldCheck, Sparkles, Star, Stethoscope } from "lucide-react";
import { Container } from "@/components/ui/container";
import { Section } from "@/components/ui/section";
import { Accordion } from "@/components/ui/accordion";
import { DoctorsGrid } from "@/components/kheni/doctors-grid";
import { MediaPlaceholder } from "@/components/kheni/media-placeholder";
import { ProblemsInteractive } from "@/components/kheni/problems-interactive";
import { SectionHeading } from "@/components/kheni/section-heading";
import { homepageFaqs, resources, site, treatments } from "@/content/site";
import { whatsappUrl } from "@/lib/links";

const trust = [
  { icon: Stethoscope, title: "Specialist-led care", copy: "Treatment planned around diagnosis, clinical need and long-term oral health." },
  { icon: Microscope, title: "Advanced diagnostics", copy: "Feature only technology actually available at the clinic after verification." },
  { icon: ShieldCheck, title: "Patient-first planning", copy: "Clear explanations, options, consent and practical aftercare." },
  { icon: Globe2, title: "International support", copy: "A dedicated pathway for NRI and overseas patients travelling to Surat." },
];

const journey = ["Consultation", "Diagnosis", "Treatment plan", "Treatment", "Aftercare"];

export default function Home() {
  return (
    <>
      <section className="relative overflow-hidden bg-ink text-white">
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_75%_24%,rgba(198,161,91,.18),transparent_30%),radial-gradient(circle_at_15%_80%,rgba(198,161,91,.08),transparent_30%)]" />
        <Container width="7xl" className="relative grid min-h-[78vh] items-center gap-12 py-16 lg:grid-cols-[1.04fr_.96fr] lg:py-24">
          <div>
            <div className="inline-flex items-center gap-2 rounded-full border border-gold/25 bg-gold/8 px-3 py-1.5 text-xs font-medium uppercase tracking-[.18em] text-gold"><Sparkles className="size-3.5" />Kheni Elite · Surat</div>
            <h1 className="mt-7 max-w-4xl font-serif text-[clamp(3.5rem,7vw,7.3rem)] leading-[.87] tracking-[-.055em]">Precision dentistry.<br/><span className="gold-text">Confident smiles.</span></h1>
            <p className="mt-7 max-w-xl text-base leading-7 text-white/60 sm:text-lg">Specialist dental, implant and restorative care designed around clarity, comfort and long-term outcomes for Surat, NRI and international patients.</p>
            <div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/contact#book" data-track="appointment_start" data-placement="home_hero" className="inline-flex h-13 items-center justify-center gap-2 rounded-full bg-gold px-6 text-sm font-semibold text-ink">Book consultation <ArrowRight className="size-4" /></Link><a href={whatsappUrl()} target="_blank" rel="noreferrer" data-track="whatsapp_click" data-placement="home_hero" className="inline-flex h-13 items-center justify-center gap-2 rounded-full border border-white/15 px-6 text-sm font-semibold text-white"><MessageCircle className="size-4 text-gold" /> WhatsApp</a></div>
            <div className="mt-10 grid max-w-xl grid-cols-3 divide-x divide-white/10 border-y border-white/10 py-5"><div className="pr-4"><div className="flex items-center gap-1 font-serif text-2xl text-gold"><Star className="size-4 fill-current" />{site.rating}</div><p className="mt-1 text-[.68rem] uppercase tracking-[.16em] text-white/40">Google rating*</p></div><div className="px-4"><p className="font-serif text-2xl text-gold">{site.reviewCount}</p><p className="mt-1 text-[.68rem] uppercase tracking-[.16em] text-white/40">Reviews*</p></div><div className="pl-4"><p className="font-serif text-2xl text-gold">{site.yearsExperience}</p><p className="mt-1 text-[.68rem] uppercase tracking-[.16em] text-white/40">Experience*</p></div></div>
            <p className="mt-3 text-[.65rem] text-white/30">*Placeholder proof points must be verified immediately before launch.</p>
          </div>
          <div className="relative"><MediaPlaceholder label="Hero: premium real portrait of lead doctor in Kheni Elite clinic" className="min-h-[32rem] lg:min-h-[39rem]" /><div className="absolute -bottom-5 -left-3 max-w-xs rounded-2xl border border-gold/20 bg-[#131311]/95 p-5 shadow-2xl backdrop-blur"><p className="text-xs uppercase tracking-[.18em] text-gold">Our philosophy</p><p className="mt-2 font-serif text-xl">Explain clearly. Plan carefully. Treat responsibly.</p></div></div>
        </Container>
      </section>

      <section className="border-b border-border bg-background"><Container width="7xl" className="grid md:grid-cols-2 lg:grid-cols-4">{trust.map((item) => <div key={item.title} className="border-border px-5 py-8 first:pl-0 md:[&:nth-child(odd)]:border-r lg:border-r lg:last:border-r-0"><item.icon className="size-5 text-gold" /><h2 className="mt-4 font-serif text-xl">{item.title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{item.copy}</p></div>)}</Container></section>

      <Section spacing="lg"><Container width="7xl"><SectionHeading eyebrow="Comprehensive care" title="Expertise where it matters. Care that feels personal." copy="A focused treatment architecture inspired by premium dental practices, built around what patients need to understand rather than a wall of procedure names."/><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{treatments.map((t, index) => <Link key={t.slug} href={`/treatments/${t.slug}`} data-track="treatment_view" data-placement="home_services" className="group flex min-h-72 flex-col rounded-[1.5rem] border border-border bg-card p-6 transition duration-300 hover:-translate-y-1 hover:border-gold/40 hover:shadow-xl"><div className="flex justify-between"><span className="font-mono text-xs text-gold">0{index+1}</span><ArrowRight className="size-4 -rotate-45 text-muted-foreground transition-transform group-hover:rotate-0 group-hover:text-gold" /></div><div className="mt-auto"><p className="text-xs uppercase tracking-[.16em] text-muted-foreground">{t.eyebrow}</p><h3 className="mt-3 font-serif text-2xl">{t.title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{t.short}</p></div></Link>)}</div></Container></Section>

      <Section className="bg-ink text-white" spacing="lg"><Container width="7xl"><SectionHeading eyebrow="Problems we treat" title="Not sure which treatment you need? Start with what’s bothering you." copy="Patients think in problems, not procedure names. This interactive discovery layer helps them find the right educational path without self-diagnosing."/><div className="mt-12"><ProblemsInteractive limit={6} /></div><div className="mt-8 text-center"><Link href="/problems-we-treat" className="inline-flex items-center gap-2 text-sm font-semibold text-gold">Explore all dental concerns <ArrowRight className="size-4" /></Link></div></Container></Section>

      <Section spacing="lg"><Container width="7xl"><div className="flex flex-col gap-8 lg:flex-row lg:items-end lg:justify-between"><SectionHeading eyebrow="Specialist profiles" title="Meet the people behind your care." copy="Use verified credentials, real portraits and meaningful specialties. This is where the premium black-and-gold doctor profile direction becomes most visible."/><Link href="/doctors" className="inline-flex items-center gap-2 text-sm font-semibold text-gold">Meet the team <ArrowRight className="size-4" /></Link></div><div className="mt-12"><DoctorsGrid /></div></Container></Section>

      <Section className="bg-[#f1eee7]" spacing="lg"><Container width="7xl"><div className="grid gap-12 lg:grid-cols-2 lg:items-center"><MediaPlaceholder label="Technology: real CBCT / scanner / treatment-room photography" className="min-h-[34rem]"/><div><SectionHeading eyebrow="Technology with purpose" title="Show patients why the technology matters, not just what it’s called." copy="Replace these placeholders with equipment the clinic genuinely owns and explain the patient benefit in plain language."/><div className="mt-8 grid gap-4"><div className="rounded-2xl bg-white p-5"><p className="font-serif text-xl">Digital diagnostics</p><p className="mt-2 text-sm text-muted-foreground">Use actual equipment details to explain planning, clarity and patient experience.</p></div><div className="rounded-2xl bg-white p-5"><p className="font-serif text-xl">Precision treatment planning</p><p className="mt-2 text-sm text-muted-foreground">Connect clinical technology to informed decisions rather than generic “advanced technology” claims.</p></div></div><Link href="/clinic-technology" className="mt-7 inline-flex items-center gap-2 text-sm font-semibold text-gold">Explore the clinic <ArrowRight className="size-4" /></Link></div></div></Container></Section>

      <Section className="bg-ink text-white" spacing="lg"><Container width="7xl"><div className="grid gap-12 lg:grid-cols-[1.08fr_.92fr] lg:items-center"><div><SectionHeading eyebrow="International patients" title="Travelling to Surat for dental care? Plan before you fly." copy="A dedicated pathway for NRI and overseas patients, with transparent coordination before travel and clear aftercare after they return home."/><div className="mt-8 grid gap-3 sm:grid-cols-2">{["Pre-arrival coordination","Appointment sequencing","Travel & stay guidance*","Post-treatment follow-up"].map(item => <div key={item} className="flex items-center gap-3 rounded-xl border border-white/10 p-4 text-sm text-white/75"><HeartHandshake className="size-4 text-gold" />{item}</div>)}</div><p className="mt-3 text-xs text-white/35">*Publish only services the clinic confirms it genuinely provides.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/international-patients" className="rounded-full bg-gold px-5 py-3 text-sm font-semibold text-ink">International patient guide</Link><a href={whatsappUrl("Hello Kheni Elite, I am an international/NRI patient and would like information about planning dental care in Surat.")} target="_blank" rel="noreferrer" data-track="international_patient_contact" data-placement="home_international" className="rounded-full border border-white/15 px-5 py-3 text-sm">Contact coordinator</a></div></div><MediaPlaceholder label="International patients: real clinic / Surat / hospitality imagery" className="min-h-[32rem]"/></div></Container></Section>

      <Section spacing="lg"><Container width="7xl"><div className="grid gap-12 lg:grid-cols-[.85fr_1.15fr]"><div><SectionHeading eyebrow="Patient journey" title="Know what happens next." copy="A clear process reduces anxiety and makes the clinic feel organized before the first visit."/><div className="mt-9 divide-y divide-border border-y border-border">{journey.map((item,index)=><div key={item} className="flex items-center gap-5 py-5"><span className="font-mono text-xs text-gold">0{index+1}</span><span className="font-serif text-xl">{item}</span></div>)}</div></div><div><SectionHeading eyebrow="Real patient proof" title="Reputation should be visible, not buried." copy="Use selected genuine reviews and consented cases here. Never fabricate testimonials, case counts or treatment outcomes."/><div className="mt-8 rounded-[2rem] border border-border bg-card p-7 sm:p-9"><div className="flex gap-1 text-gold">{Array.from({length:5}).map((_,i)=><Star key={i} className="size-4 fill-current" />)}</div><blockquote className="mt-6 font-serif text-3xl leading-tight">“Replace this with a selected, genuine Google review after launch approval.”</blockquote><p className="mt-5 text-sm text-muted-foreground">Verified patient review placeholder</p><a href={site.reviewUrl} target="_blank" rel="noreferrer" data-track="review_click" data-placement="home_reviews" className="mt-8 inline-flex items-center gap-2 text-sm font-semibold text-gold">Read Google reviews <ArrowRight className="size-4" /></a></div></div></div></Container></Section>

      <Section className="bg-[#f1eee7]" spacing="lg"><Container width="7xl"><SectionHeading eyebrow="Patient resources" title="Useful before, during and after treatment." copy="Inspired by Dallas Periodontal’s resource-first approach, this area becomes Kheni’s patient education library and an SEO asset over time."/><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{resources.slice(0,6).map((resource,index)=><Link key={resource.title} href={resource.href} data-track="resource_download" data-placement="home_resources" className="group rounded-2xl bg-white p-6"><div className="flex items-center justify-between"><Award className="size-5 text-gold"/><span className="font-mono text-xs text-muted-foreground">0{index+1}</span></div><h3 className="mt-7 font-serif text-2xl">{resource.title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{resource.description}</p><span className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-gold">Open resource <ArrowRight className="size-4 transition-transform group-hover:translate-x-1" /></span></Link>)}</div></Container></Section>

      <Section spacing="lg"><Container width="7xl"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><SectionHeading eyebrow="Common questions" title="Clear answers before the appointment." copy="Educational content should be clinician-reviewed, conservative and easy to understand."/><Accordion items={homepageFaqs} className="bg-card" /></div></Container></Section>

      <section className="bg-gold py-16 text-ink sm:py-20"><Container width="7xl" className="grid gap-7 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="text-xs font-semibold uppercase tracking-[.22em]">Start a conversation</p><h2 className="mt-3 max-w-3xl font-serif text-4xl leading-none tracking-[-.04em] sm:text-5xl">Ready to discuss your dental care?</h2><p className="mt-4 max-w-xl text-sm leading-6 text-ink/65">Request appointment options by WhatsApp or contact the clinic directly. Clinical recommendations require an appropriate professional assessment.</p></div><div className="flex flex-col gap-3 sm:flex-row"><Link href="/contact#book" data-track="appointment_start" data-placement="home_final_cta" className="rounded-full bg-ink px-6 py-3.5 text-center text-sm font-semibold text-white">Book consultation</Link><a href={whatsappUrl()} target="_blank" rel="noreferrer" data-track="whatsapp_click" data-placement="home_final_cta" className="rounded-full border border-ink/20 px-6 py-3.5 text-center text-sm font-semibold">WhatsApp</a></div></Container></section>
    </>
  );
}
