/**
 * Colour contrast record.
 *
 *   node scripts/contrast-report.mjs
 *
 * Reads the palette straight out of src/app/globals.css rather than keeping
 * its own copy of the hex values. An earlier version hardcoded them, and
 * after the September palette change it happily reported "0 failing" while
 * testing colours the site no longer used. A checker that can go stale is
 * worse than no checker, because it is trusted.
 *
 * Threshold is WCAG AA for normal text, 4.5:1. Marks, fills and decorative
 * shapes are held to 3:1 and are marked as such.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const css = readFileSync(`${ROOT}/src/app/globals.css`, "utf8");

/** Pull every `--name: #rrggbb;` declaration out of the stylesheet. */
const TOKENS = Object.fromEntries([...css.matchAll(/(--[a-z0-9-]+)\s*:\s*(#[0-9a-fA-F]{6})\s*;/g)].map((m) => [m[1], m[2].toLowerCase()]));

const need = (name) => {
  const v = TOKENS[name];
  if (!v) throw new Error(`Token ${name} not found in globals.css. Update this script alongside the palette.`);
  return v;
};

const hex = (h) => [0, 2, 4].map((i) => parseInt(h.slice(1).slice(i, i + 2), 16));
const lin = (c) => { c /= 255; return c <= 0.04045 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4); };
const L = (h) => { const [r, g, b] = hex(h); return 0.2126 * lin(r) + 0.7152 * lin(g) + 0.0722 * lin(b); };
const CR = (a, b) => { const l1 = L(a), l2 = L(b); const [hi, lo] = l1 > l2 ? [l1, l2] : [l2, l1]; return (hi + 0.05) / (lo + 0.05); };

const C = {
  ink: need("--brand-ink"), ink2: need("--brand-ink-2"), charcoal: need("--brand-charcoal"),
  ivory: need("--brand-ivory"), white: need("--brand-white"), sand: need("--brand-sand"), inkSoft: need("--brand-ink-soft"),
  gold: need("--brand-gold"), goldText: need("--brand-gold-text"), goldSoft: need("--brand-gold-soft"),
  goldTint: need("--brand-gold-tint"), goldDeep: need("--brand-gold-deep"), roseMark: need("--brand-rose-mark"),
  sky: need("--surface-sky"), skyText: need("--surface-sky-text"),
  mint: need("--surface-mint"), mintText: need("--surface-mint-text"),
  peach: need("--surface-peach"), peachText: need("--surface-peach-text"),
  lavender: need("--surface-lavender"), lavenderText: need("--surface-lavender-text"),
  butter: need("--surface-butter"), butterText: need("--surface-butter-text"),
};

const LIGHT = ["ivory", "white", "sand", "goldTint", "sky", "mint", "peach", "lavender", "butter"];
const rows = [];
const add = (fg, bg, use, min = 4.5) => {
  const r = CR(C[fg], C[bg]);
  rows.push({ pair: `${fg} on ${bg}`, use, ratio: r.toFixed(2), min, pass: r >= min });
};

for (const bg of LIGHT) {
  add("charcoal", bg, "body and headings");
  add("inkSoft", bg, "muted body");
  add("goldText", bg, "gold links, eyebrows, the highlighted word");
}
for (const bg of ["ink", "ink2"]) {
  add("ivory", bg, "body on dark");
  add("gold", bg, "gold accent, eyebrows and stars on dark");
  add("goldSoft", bg, "hover and the highlighted word on dark");
}
add("ink", "gold", "ink label on a gold button");
add("ink", "goldSoft", "ink label on a gold hover state");
add("goldDeep", "ivory", "bronze rule and underline, graphics threshold", 3);
add("skyText", "sky", "eyebrow on the sky field");
add("mintText", "mint", "eyebrow on the mint field");
add("peachText", "peach", "eyebrow on the peach field");
add("lavenderText", "lavender", "eyebrow on the lavender field");
add("butterText", "butter", "eyebrow on the butter field");
/* The logo mark is artwork, not text, so it is held to the 3:1 graphics rule. */
add("roseMark", "ivory", "the logo's rose K on light, graphics threshold", 3);

const fails = rows.filter((r) => !r.pass);

let md = `# Colour contrast record

Generated by \`scripts/contrast-report.mjs\`, which reads the palette out of
\`src/app/globals.css\` so it cannot drift from what the site actually renders.
Threshold is WCAG AA for normal text, 4.5:1. The one graphics pair is held to
3:1 and says so.

Re-generate after any palette change:

    node scripts/contrast-report.mjs

| Pair | Where it is used | Ratio | Needs | Result |
|---|---|---:|---:|---|
`;
for (const r of rows) md += `| \`${r.pair}\` | ${r.use} | ${r.ratio}:1 | ${r.min}:1 | ${r.pass ? "AA" : "**FAIL**"} |\n`;
md += `\n**${rows.length} pairs checked, ${fails.length} failing.**\n`;
md += `
## Why gold needs four weights

\`${C.gold}\` is the site's gold. It reaches ${CR(C.gold, C.ink).toFixed(2)}:1 on near-black, which is
excellent, and ${CR(C.gold, C.ivory).toFixed(2)}:1 on ivory, which is unusable. One gold cannot carry
both jobs, so the work is split:

| Token | Value | Job |
|---|---|---|
| \`--brand-gold\` | ${C.gold} | dark surfaces, fills, stars, the primary button |
| \`--brand-gold-text\` | ${C.goldText} | small text, links and eyebrows on light surfaces |
| \`--brand-gold-soft\` | ${C.goldSoft} | hover on dark, hairlines |
| \`--brand-gold-tint\` | ${C.goldTint} | the lightest gold field |
| \`--brand-gold-deep\` | ${C.goldDeep} | bronze, for a rule or an underline |

The logo's rose (\`${C.roseMark}\`) is not part of this system. It appears only in
the K of the mark, where it is artwork rather than text.
`;
writeFileSync(`${ROOT}/docs/COLOUR-CONTRAST.md`, md);
console.log(`${rows.length} pairs, ${fails.length} failing`);
if (fails.length) console.log(fails.map((f) => `  FAIL ${f.pair} ${f.ratio}:1 needs ${f.min}:1`).join("\n"));
