import { writeFileSync } from "node:fs";
const hex=h=>{h=h.replace('#','');return [0,2,4].map(i=>parseInt(h.slice(i,i+2),16));};
const lin=c=>{c/=255;return c<=0.04045?c/12.92:Math.pow((c+0.055)/1.055,2.4);};
const L=h=>{const [r,g,b]=hex(h);return 0.2126*lin(r)+0.7152*lin(g)+0.0722*lin(b);};
const CR=(a,b)=>{const l1=L(a),l2=L(b);const [hi,lo]=l1>l2?[l1,l2]:[l2,l1];return (hi+0.05)/(lo+0.05);};
const C={ink:"#121011",ink2:"#1b1819",charcoal:"#363435",ivory:"#faf6f0",white:"#ffffff",sand:"#eee7dd",
  rose:"#9b6665",roseStrong:"#b87872",roseText:"#895a59",roseOnDark:"#b88c8a",roseSoft:"#d9b0aa",blush:"#f1e3df",
  champagne:"#d3b985",champagneText:"#7b6235",inkSoft:"#57534e",
  sage:"#e2eae2",sageText:"#467157",blue:"#e6edf1",blueText:"#3a6b87",butter:"#f4ebcb",butterText:"#83651d",lav:"#eeeaf2",lavText:"#5d4e96"};
const LIGHT=["ivory","white","sand","blush","sage","blue","butter","lav"];
const rows=[];
const add=(fg,bg,use,min=4.5)=>{const r=CR(C[fg],C[bg]);rows.push({pair:`${fg} on ${bg}`,use,ratio:r.toFixed(2),need:min,pass:r>=min});};
for (const bg of LIGHT) { add("charcoal",bg,"body and headings"); add("inkSoft",bg,"muted body"); add("roseText",bg,"rose links, labels, highlighted word"); add("champagneText",bg,"champagne small text"); }
for (const bg of ["ink","ink2"]) { add("ivory",bg,"body on dark"); add("roseOnDark",bg,"rose accent on dark"); add("champagne",bg,"stars and proof numerals"); add("roseSoft",bg,"highlighted word on dark"); }
add("ink","roseStrong","primary button label");
add("ink","champagne","champagne button label");
add("ivory","whatsapp" in C?"whatsapp":"ink","");rows.pop();
add("sageText","sage","eyebrow on sage"); add("blueText","blue","eyebrow on blue-grey");
add("butterText","butter","eyebrow on butter"); add("lavText","lav","eyebrow on lavender");
const fails=rows.filter(r=>!r.pass);
let md=`# Colour contrast record\n\nGenerated by scripts, not by eye. Every pair below is a combination the site\nactually renders. Threshold is WCAG AA for normal text, 4.5:1.\n\nRe-generate after any palette change:\n\n    node scripts/contrast-report.mjs\n\n| Pair | Where it is used | Ratio | Result |\n|---|---|---:|---|\n`;
for (const r of rows) md += `| \`${r.pair}\` | ${r.use} | ${r.ratio}:1 | ${r.pass?"AA":"**FAIL**"} |\n`;
md += `\n**${rows.length} pairs checked, ${fails.length} failing.**\n`;
md += `\n## Why there are four roses\n\nThe logo's own rose (#9B6665) cannot do every job and stay legible:\n\n- as small text on ivory it reaches only 4.35:1\n- as a button fill it reaches 4.05:1 with an ink label and 4.35:1 with ivory\n- as text on ink it reaches 4.05:1\n\nSo the brand rose is kept for marks, fills and shapes, where contrast rules\nask for 3:1 rather than 4.5:1, and three contrast-solved siblings carry the\nwork it cannot:\n\n| Token | Value | Job |\n|---|---|---|\n| \`--brand-rose\` | #9B6665 | the logo mark, fills, decorative shapes |\n| \`--brand-rose-strong\` | #B87872 | primary button fill, ink label at 5.39:1 |\n| \`--brand-rose-text\` | #895A59 | links, labels and the highlighted word on light |\n| \`--brand-rose-on-dark\` | #B88C8A | the same jobs on ink |\n\nChampagne needed the same treatment. #D3B985 is 9.97:1 on ink and perfect for\nstars, but only 3.69:1 as small text on ivory, so light surfaces use the\ndeeper #7B6235 instead.\n`;
writeFileSync("/home/user/Kheni-Dental/docs/COLOUR-CONTRAST.md", md);
console.log(`${rows.length} pairs, ${fails.length} failing`);
if (fails.length) console.log(fails.map(f=>`  FAIL ${f.pair} ${f.ratio}`).join("\n"));
