import type { Metadata } from "next";
import { PageHero } from "@/components/kheni/page-hero";
import { Container } from "@/components/ui/container";
import { Section } from "@/components/ui/section";
import { resources } from "@/content/site";
export const metadata:Metadata={title:"Dental Patient Guides",description:"Practical dental guides from Kheni Dental, Surat: what to bring to a first visit, how implant planning works, root canal aftercare and calmer visits for kids."};
const guidance={
  "first-visit":["Bring the names of any medicines you take, including anything for blood pressure, diabetes or blood thinning, and old X-rays or reports if you still have them.","Say when the problem started, what makes it worse and whether it disturbs your sleep. Those three details narrow down the cause faster than anything else.","Before you leave, ask what needs attention now, what can safely wait and what the alternatives are. Write the answers down while they are fresh."],
  "implant-guide":["An implant has two halves: the part placed in the bone and the tooth fitted on top. Ask about both, and check that any two plans you compare cover the same stages.","Ask how much time is expected between stages and what you will be wearing while you wait. That is the part most people want to know and least often think to ask.","Ask what affects how long an implant lasts in your case. Bone, gum health, bite, smoking and grinding all play a part, and so does the cleaning routine you keep up at home."],
  "root-canal-aftercare":["The tooth can stay tender to bite on for some days, especially if it was painful before treatment. Chew on the other side until it settles and follow the instructions you were given.","A treated tooth is not finished until it is properly rebuilt. Ask what your tooth needs next, whether that is a filling or a crown, and by when it should be done.","Call the clinic if the pain is getting worse instead of easing, if the gum or face swells, or if anything feels different from what was explained to you."],
  "kids-visit":["Keep the build-up short and ordinary. Avoid words like injection, drill or pain, even in reassurance. Children latch on to the word and not the reassurance around it.","Ask for a time when your child is usually rested and fed rather than the end of a long school day. A tired child finds everything harder.","Tell the team beforehand if your child is frightened or had a rough time at another clinic. Knowing that in advance changes how the first few minutes are handled."],
} as const;
export default function ResourcesPage(){return <><PageHero eyebrow="Patient resources" title="Know what to ask before you sit down." copy="Four short guides written around the questions people actually ask at the clinic. They will not tell you which treatment you need, but they should help you walk in prepared and leave with fewer doubts."/><Section spacing="lg"><Container width="7xl"><div className="space-y-8">{resources.map(resource=>{const id=resource.href.split('#')[1] as keyof typeof guidance;return <article key={resource.title} id={id} className="scroll-mt-28 rounded-[2rem] border border-border bg-card p-7 sm:p-9"><p className="text-xs uppercase tracking-[.18em] text-gold">Patient guide</p><h2 className="mt-3 font-serif text-3xl">{resource.title}</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">{resource.description}</p><ul className="mt-6 grid gap-3 md:grid-cols-3">{guidance[id].map(item=><li key={item} className="rounded-2xl bg-[#f1eee7] p-5 text-sm leading-6 text-muted-foreground">{item}</li>)}</ul></article>})}</div><p className="mt-8 text-sm leading-6 text-muted-foreground">These guides are general information, written to help you prepare and ask better questions. They cannot tell you what is happening in your own mouth, because that needs an examination. If anything here does not match what you have been told at the clinic, ask the doctor treating you.</p></Container></Section></>}
