import type { Metadata } from "next";
import { PageHero } from "@/components/kheni/page-hero";
import { Container } from "@/components/ui/container";
import { Section } from "@/components/ui/section";
import { resources } from "@/content/site";
export const metadata:Metadata={title:"Patient Resources | Kheni Dental",description:"Plain-language dental guides for first visits, implants, root canal aftercare and children's dental visits at Kheni Dental."};
const guidance={
  "first-visit":["Bring a list of medicines if the dentist needs your medical history during the consultation.","Tell the dentist what is bothering you and how long it has been happening.","Ask what is urgent, what can wait and what alternatives exist."],
  "implant-guide":["Implant suitability depends on examination, bone, gums, health and the restoration being planned.","Ask about the full sequence, expected visits, healing time and maintenance before treatment.","Do not compare implant plans only by price. The clinical situation and final restoration matter."],
  "root-canal-aftercare":["Some tenderness can occur after treatment. Follow the instructions given by your dentist.","Avoid assuming every treated tooth needs the same restoration. Ask what your tooth needs next.","Contact the clinic if pain or swelling is severe, worsening or different from what was explained."],
  "kids-visit":["Use calm, simple language before the visit rather than describing frightening details.","Bring questions about brushing, diet, cavities or habits so the visit is useful for parents too.","Tell the clinic in advance if your child is very anxious or has had a difficult dental experience."],
} as const;
export default function ResourcesPage(){return <><PageHero eyebrow="Patient resources" title="Better decisions start with better information." copy="Short, practical guides to help you prepare for visits, understand common treatment journeys and know what to ask your dentist."/><Section spacing="lg"><Container width="7xl"><div className="space-y-8">{resources.map(resource=>{const id=resource.href.split('#')[1] as keyof typeof guidance;return <article key={resource.title} id={id} className="scroll-mt-28 rounded-[2rem] border border-border bg-card p-7 sm:p-9"><p className="text-xs uppercase tracking-[.18em] text-gold">Patient guide</p><h2 className="mt-3 font-serif text-3xl">{resource.title}</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">{resource.description}</p><ul className="mt-6 grid gap-3 md:grid-cols-3">{guidance[id].map(item=><li key={item} className="rounded-2xl bg-[#f1eee7] p-5 text-sm leading-6 text-muted-foreground">{item}</li>)}</ul></article>})}</div><p className="mt-8 text-sm leading-6 text-muted-foreground">These resources are general education and should be reviewed by the treating doctors before final publication. They do not replace individual clinical advice.</p></Container></Section></>}
