import type { Metadata } from "next";
import { PageHero } from "@/components/kheni/page-hero";
import { MediaPlaceholder } from "@/components/kheni/media-placeholder";
import { SectionHeading } from "@/components/kheni/section-heading";
import { Container } from "@/components/ui/container";
import { Section } from "@/components/ui/section";

export const metadata:Metadata={title:"Clinic & Dental Technology | Kheni Dental",description:"A look at Kheni Dental clinic spaces and the technology used for diagnosis and treatment planning. Final equipment details will be added after clinic verification."};
const placeholders=[['Diagnostics','Add the exact imaging and diagnostic systems only after the clinic confirms the equipment available at each branch.'],['Digital workflow','If the clinic uses scanners or digital design tools, explain what they change for the patient rather than listing model names.'],['Sterilisation and hygiene','Describe the actual sterilisation workflow and infection-control practices after the clinic provides verified details.'],['Treatment rooms','Use real photography to show the environment patients will actually visit.']];
export default function ClinicTechnologyPage(){return <><PageHero eyebrow="Clinic & technology" title="Show the real clinic. Explain what the technology changes for the patient." copy="This section is intentionally factual. Equipment, sterilisation claims and advanced technology details will only be published after the clinic verifies them."/><Section spacing="lg"><Container width="7xl"><div className="grid gap-5 md:grid-cols-2">{placeholders.map(([title,copy])=><article key={title} className="rounded-[2rem] border border-border bg-card p-7"><h2 className="font-serif text-3xl">{title}</h2><p className="mt-4 text-sm leading-6 text-muted-foreground">{copy}</p></article>)}</div></Container></Section><Section className="bg-ink text-white" spacing="lg"><Container width="7xl"><SectionHeading eyebrow="Photography plan" title="Real spaces build more trust than stock dental imagery." copy="The final site should show the exterior, reception, treatment rooms, team at work and verified equipment at both branches."/><div className="mt-10 grid gap-5 md:grid-cols-2"><MediaPlaceholder label="Yogi Chowk clinic photography" className="min-h-[28rem]"/><MediaPlaceholder label="Hirabaug clinic photography" className="min-h-[28rem]"/></div></Container></Section></>}
