import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Star } from "lucide-react";
import { PageHero } from "@/components/kheni/page-hero";
import { Container } from "@/components/ui/container";
import { Section } from "@/components/ui/section";
import { locations } from "@/content/site";

export const metadata:Metadata={title:"Patient Reviews | Kheni Dental Surat",description:"Review signals for Kheni Dental in Surat, including the Yogi Chowk Google profile and Hirabaug public ratings."};
export default function ReviewsPage(){return <><PageHero eyebrow="Patient feedback" title="Choosing a dentist is personal. Real patient experiences help." copy="The final website will feature selected genuine patient stories with permission. Until then, we show only review signals that can be traced to public profiles."/><Section spacing="lg"><Container width="7xl"><div className="grid gap-5 md:grid-cols-2">{locations.map(location=><article key={location.slug} className="rounded-[2rem] border border-border bg-card p-7"><p className="text-xs uppercase tracking-[.18em] text-gold">{location.shortName}</p>{location.rating&&<div className="mt-5 flex items-end gap-3"><span className="flex items-center gap-2 font-serif text-5xl"><Star className="size-7 fill-current text-gold"/>{location.rating}</span><span className="pb-1 text-sm text-muted-foreground">{location.reviewCount} ratings · {location.reviewSource}</span></div>}<p className="mt-5 text-sm leading-6 text-muted-foreground">Public reviews for Kheni Dental commonly mention helpful staff, clear explanations, cooperation and a comfortable clinic experience. Individual experiences can vary.</p><a href={location.mapsUrl} target="_blank" rel="noreferrer" className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-gold">Open map profile <ArrowRight className="size-4"/></a></article>)}</div><div className="mt-8 rounded-[2rem] bg-[#f1eee7] p-7"><h2 className="font-serif text-3xl">Patient stories will be added carefully.</h2><p className="mt-4 max-w-3xl text-sm leading-6 text-muted-foreground">For the final site, use real reviews and case stories only. Avoid rewriting a patient's experience into exaggerated marketing claims, and obtain consent before connecting a testimonial to identifiable treatment details or photographs.</p><Link href="/contact" className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-gold">Contact the clinic <ArrowRight className="size-4"/></Link></div></Container></Section></>}
