import type { Metadata } from "next";
import { Globe2, MessageCircle, Plane, ShieldCheck, type LucideIcon } from "lucide-react";
import { ConsultationForm } from "@/components/kheni/consultation-form";
import { MediaPlaceholder } from "@/components/kheni/media-placeholder";
import { PageHero } from "@/components/kheni/page-hero";
import { GoogleTrustCard } from "@/components/kheni/google-trust-card";
import { SectionHeading } from "@/components/kheni/section-heading";
import { Container } from "@/components/ui/container";
import { Section } from "@/components/ui/section";
import { whatsappUrl } from "@/lib/links";

export const metadata:Metadata={title:"NRI & International Dental Patients in Surat",description:"Travelling to Surat and thinking about dental care while you are here? Share your dates first, and the clinic can explain what is realistic to plan."};
const benefits: { icon: LucideIcon; title: string }[] = [
  { icon: Globe2, title: "For patients travelling in from abroad" },
  { icon: Plane, title: "Planning built around your dates" },
  { icon: ShieldCheck, title: "Straight answers about what will not fit" },
  { icon: MessageCircle, title: "Ask the clinic directly on WhatsApp" },
];

const steps=[['1','Send your dates and your concern','Tell us roughly when you will be in Surat and what is troubling you. One message is enough to begin.'],['2','Hear what fits the time you have','The clinic can say whether a consultation, an examination with imaging, or actual treatment is realistic within your stay.'],['3','Book your travel around the plan','Some treatment needs healing time between stages, so it may need more than one trip. Please do not fix your dates around an estimate taken off a website.'],['4','Agree what happens after you leave','Before you leave Surat, ask what review will be needed, which records to take with you and how to reach the clinic if something does not feel right.']];
export default function InternationalPage(){return <><PageHero eyebrow="International & NRI patients" title="A short stay needs a realistic plan." copy="If you are coming to Surat from abroad and want dental care while you are here, write to the clinic before you book anything. Once we know your dates and what is troubling you, we can talk honestly about what can be assessed and planned in the time you have."/><Section spacing="lg"><Container width="7xl"><div className="grid gap-12 lg:grid-cols-[1.05fr_.95fr] lg:items-center"><div><SectionHeading eyebrow="Planning from abroad" title="Timing is the hardest thing to judge from abroad." copy="Some dental work can be finished in one appointment. Other treatment needs an examination first, then healing time, then a review. Until a dentist has looked at your case, nobody can honestly tell you how many visits it will take, and we would rather say that plainly than hand you a number to build your travel around."/><div className="mt-8 grid gap-3 sm:grid-cols-2">{benefits.map(({icon: Icon,title})=><div key={title} className="flex items-center gap-3 rounded-2xl border border-border bg-card p-4 text-sm"><Icon className="size-5 text-gold"/>{title}</div>)}</div></div><div><MediaPlaceholder label="Inside the clinic in Surat" className="min-h-[32rem]"/><GoogleTrustCard className="mt-5" placement="international_google" /></div></div></Container></Section><Section className="bg-ink text-white" spacing="lg"><Container width="7xl"><SectionHeading eyebrow="Before you travel" title="How the planning usually goes."/><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{steps.map(([n,title,copy])=><div key={n} className="rounded-2xl border border-white/10 p-6"><span className="font-mono text-xs text-gold">0{n}</span><h2 className="mt-7 font-serif text-2xl">{title}</h2><p className="mt-3 text-sm leading-6 text-white/55">{copy}</p></div>)}</div></Container></Section><Section spacing="lg"><Container width="7xl"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><SectionHeading eyebrow="International enquiry" title="A few lines are enough to start." copy="The form opens a WhatsApp message with your basics already filled in. Lead with your dates and the concern you want looked at, and the team can also tell you which of the two Surat clinics, Swastik Plaza or Hirabaug, suits what you need. Please keep reports and medical history out of that first message."/><a href={whatsappUrl("Hello Kheni Dental, I am an international/NRI patient and would like information about planning a dental visit in Surat.")} target="_blank" rel="noreferrer" className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-gold"><MessageCircle className="size-4"/>Open WhatsApp directly</a></div><ConsultationForm international/></div></Container></Section></>}
