import type { Metadata } from "next";
import { Globe2, MessageCircle, Plane, ShieldCheck, type LucideIcon } from "lucide-react";
import { ConsultationForm } from "@/components/kheni/consultation-form";
import { MediaPlaceholder } from "@/components/kheni/media-placeholder";
import { PageHero } from "@/components/kheni/page-hero";
import { GoogleTrustCard } from "@/components/kheni/google-trust-card";
import { SectionHeading } from "@/components/kheni/section-heading";
import { Container } from "@/components/ui/container";
import { Section } from "@/components/ui/section";
import { whatsappUrl } from "@/lib/links";

export const metadata:Metadata={title:"International & NRI Dental Patients in Surat",description:"Plan a dental enquiry with Kheni Dental in Surat before travelling. Information for NRI and international patients considering dental care during a visit to Surat."};
const benefits: { icon: LucideIcon; title: string }[] = [
  { icon: Globe2, title: "NRI and overseas enquiries" },
  { icon: Plane, title: "Visit-window planning" },
  { icon: ShieldCheck, title: "Clear treatment limitations" },
  { icon: MessageCircle, title: "Direct WhatsApp contact" },
];

const steps=[['1','Tell us your travel window','Share when you expect to be in Surat and the broad dental concern you want assessed.'],['2','Confirm what can be planned','The clinic can explain whether an initial consultation, diagnostics or treatment may fit your available time.'],['3','Keep expectations realistic','Complex treatment may require healing time or more than one visit. Do not book travel based on a website estimate alone.'],['4','Plan follow-up','Ask what follow-up may be needed after you leave Surat and what records you should keep.']];
export default function InternationalPage(){return <><PageHero eyebrow="International & NRI patients" title="Arrive with a plan, not a list of unanswered questions." copy="If you are travelling to Surat and want dental care during your stay, start the conversation before you fly. The clinic can help you understand what can realistically be assessed or planned within your visit."/><Section spacing="lg"><Container width="7xl"><div className="grid gap-12 lg:grid-cols-[1.05fr_.95fr] lg:items-center"><div><SectionHeading eyebrow="Planning from abroad" title="Good travel planning starts with honest treatment timing." copy="Dental treatment is not always a one-visit service. Some procedures require diagnostics, healing or review. We keep timelines realistic until the dentist has enough information to plan properly."/><div className="mt-8 grid gap-3 sm:grid-cols-2">{benefits.map(({icon: Icon,title})=><div key={title} className="flex items-center gap-3 rounded-2xl border border-border bg-card p-4 text-sm"><Icon className="size-5 text-gold"/>{title}</div>)}</div></div><div><MediaPlaceholder label="International patient, clinic and Surat photography" className="min-h-[32rem]"/><GoogleTrustCard className="mt-5" placement="international_google" /></div></div></Container></Section><Section className="bg-ink text-white" spacing="lg"><Container width="7xl"><SectionHeading eyebrow="A simple process" title="Plan the visit in four steps."/><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{steps.map(([n,title,copy])=><div key={n} className="rounded-2xl border border-white/10 p-6"><span className="font-mono text-xs text-gold">0{n}</span><h2 className="mt-7 font-serif text-2xl">{title}</h2><p className="mt-3 text-sm leading-6 text-white/55">{copy}</p></div>)}</div></Container></Section><Section spacing="lg"><Container width="7xl"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><SectionHeading eyebrow="International enquiry" title="Share the basics. Keep medical details private." copy="Use the form to open a WhatsApp conversation. Tell us your travel window first, and the clinic team can explain what can realistically be arranged around your visit."/><a href={whatsappUrl("Hello Kheni Dental, I am an international/NRI patient and would like information about planning a dental visit in Surat.")} target="_blank" rel="noreferrer" className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-gold"><MessageCircle className="size-4"/>Open WhatsApp directly</a></div><ConsultationForm international/></div></Container></Section></>}
