import type { Metadata } from "next";
import { Check, Globe2, MapPin, Plane, Video } from "lucide-react";
import { PageHero } from "@/components/kheni/page-hero";
import { ConsultationForm } from "@/components/kheni/consultation-form";
import { MediaPlaceholder } from "@/components/kheni/media-placeholder";
import { SectionHeading } from "@/components/kheni/section-heading";
import { Container } from "@/components/ui/container";
import { Section } from "@/components/ui/section";
export const metadata:Metadata={title:"International Patients & Dental Tourism",description:"Plan dental care in Surat with Kheni Elite's international and NRI patient coordination pathway."};
export default function InternationalPage(){const steps=[{icon:Video,title:"Before you travel",copy:"Share non-sensitive scheduling needs first. The clinic can confirm what records are appropriate to exchange through a suitable private channel."},{icon:Globe2,title:"Plan your visits",copy:"Coordinate expected appointment sequence and time in Surat after the clinical team reviews what can reasonably be planned in advance."},{icon:Plane,title:"Travel to Surat",copy:"Add verified airport, transfer and accommodation guidance only if the clinic genuinely provides or coordinates it."},{icon:Check,title:"Follow-up",copy:"Document the clinic's actual follow-up process for patients who return overseas after treatment."}];return <><PageHero eyebrow="International & NRI patients" title="Dental care in Surat, planned with fewer surprises." copy="A dedicated pathway for patients travelling to India. Clear coordination, realistic timelines and responsible follow-up should be the focus, not price hype."/><Section spacing="lg"><Container width="7xl"><div className="grid gap-12 lg:grid-cols-[1fr_.9fr] lg:items-center"><div><SectionHeading eyebrow="Why Surat" title="Position Surat as convenient and connected, without unsupported tourism claims." copy="Use verified travel facts, clinic accessibility and genuine patient-support services. Avoid calling Surat the 'best dental tourism destination' unless there is credible evidence for that claim."/><div className="mt-7 flex gap-3 rounded-2xl bg-[#f1eee7] p-5 text-sm leading-6 text-muted-foreground"><MapPin className="mt-0.5 size-5 shrink-0 text-gold"/>CONTENT NEEDED: nearest airport, estimated drive time, hotel areas, languages supported, consultation coordination, travel assistance and whether the clinic has actual NRI/international case experience.</div></div><MediaPlaceholder label="Surat / clinic / international patient welcome photography" className="min-h-[32rem]"/></div></Container></Section><Section className="bg-ink text-white" spacing="lg"><Container width="7xl"><SectionHeading eyebrow="How it works" title="A calm international patient journey."/><div className="mt-10 grid gap-4 md:grid-cols-4">{steps.map((s,i)=><article key={s.title} className="rounded-2xl border border-white/10 p-6"><s.icon className="size-5 text-gold"/><span className="mt-8 block font-mono text-xs text-white/30">0{i+1}</span><h2 className="mt-3 font-serif text-2xl">{s.title}</h2><p className="mt-3 text-sm leading-6 text-white/55">{s.copy}</p></article>)}</div></Container></Section><Section spacing="lg"><Container width="7xl"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><SectionHeading eyebrow="International enquiry" title="Start with logistics. Discuss clinical details privately." copy="This generic form moves the conversation to the clinic's WhatsApp without collecting diagnosis or medical history in the website analytics layer."/><ConsultationForm international/></div></Container></Section></>}
